# Site settings
title: Mike Mannix
email: mike.mannix@gmail.com
description: "A place for me to write about iOS/Cocoa/Apple and maybe other things."
baseurl: ""
url: "http://mannix.xyz"
highligher: pygments

# Build settings
markdown: kramdown
permalink: pretty
